In [2]:
import pandas as pd
import numpy as np

In [10]:
df=pd.read_csv('titanic.csv')
print(df.shape)
df.head()
df.info()    #okay noth head and info are giving the table

(891, 12)
<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [11]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [ ]:
df.head()    #in a diff cell it prints the proper table

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [21]:
#columns list
print(df.columns.tolist())
#for a particular column
print(df['Survived'].value_counts())  #which value has how many counts
print(df['Pclass'].unique())
#select multiple columns
print(df[['Pclass','Name','Age','Survived']].head(10))

['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']
Survived
0    549
1    342
Name: count, dtype: int64
[3 1 2]
   Pclass                                               Name   Age  Survived
0       3                            Braund, Mr. Owen Harris  22.0         0
1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0         1
2       3                             Heikkinen, Miss. Laina  26.0         1
3       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0         1
4       3                           Allen, Mr. William Henry  35.0         0
5       3                                   Moran, Mr. James   NaN         0
6       1                            McCarthy, Mr. Timothy J  54.0         0
7       3                     Palsson, Master. Gosta Leonard   2.0         0
8       3  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  27.0         1
9       2                Nasser, Mrs. Nicholas (Adele Achem)  14.0         1

Missing Values

In [27]:
#how many nulls per column
print(df.isnull().sum())
df['Age']=df['Age'].fillna(df['Age'].median())
print(df['Age'].isnull().sum())

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64
0

Filtering Rows

In [30]:
survivors=df[df['Survived']==1]
print(survivors.shape)

(342, 12)

In [36]:
#first class passengers over age 40
fc_forty=df[(df['Age']>40) & (df['Pclass']==1)]
fc_forty.head()
print(fc_forty[['Name','Age','Pclass']].head())

                                        Name   Age  Pclass
6                    McCarthy, Mr. Timothy J  54.0       1
11                  Bonnell, Miss. Elizabeth  58.0       1
35            Holverson, Mr. Alexander Oskar  42.0       1
52  Harper, Mrs. Henry Sleeper (Myna Haxtun)  49.0       1
54            Ostby, Mr. Engelhart Cornelius  65.0       1

In [40]:
#survival rate
survival_by_class=df.groupby('Pclass')['Survived'].mean()
print(survival_by_class)

Pclass
1    0.629630
2    0.472826
3    0.242363
Name: Survived, dtype: float64

In [41]:
#avg age per class
print(df.groupby('Pclass')['Age'].mean())

Pclass
1    36.812130
2    29.765380
3    25.932627
Name: Age, dtype: float64